backend:
  name: github
  repo: johnoliveira697/zero-stop-precision
  branch: main
  base_url: https://0stopprecision.com
  auth_endpoint: api/auth

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "artigos"
    label: "Artigos"
    folder: "content/artigos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título do Artigo", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD" }
      - { label: "Categoria", name: "category", widget: "string" }
      - { label: "Resumo (Excerpt)", name: "excerpt", widget: "text" }
      - { label: "Imagem de Capa", name: "coverImage", widget: "image", required: false }
      - { label: "Corpo do Texto", name: "body", widget: "markdown" }

  - name: "livros"
    label: "Livros"
    folder: "content/livros"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título do Livro", name: "title", widget: "string" }
      - { label: "Autor", name: "author", widget: "string", default: "John Oliveira" }
      - { label: "Categoria", name: "category", widget: "string" }
      - { label: "Breve Descrição", name: "description", widget: "text" }
      - { label: "Imagem da Capa", name: "image", widget: "image" }
      - { label: "Link de Compra / Afiliado", name: "link", widget: "string" }
